export default function AIVigilantComp() {
  return (
    <div>
      <h2>AI Vigilant</h2>
      <p>
        Result of AI is subject to review. Please use caution and verify the
        content generated by AI tools.
      </p>
    </div>
  );
}
